-- +goose Up
ALTER TABLE users ADD COLUMN username VARCHAR(255) NOT NULL UNIQUE;
ALTER TABLE users ADD COLUMN password VARCHAR(255) NOT NULL;

-- +goose Down
ALTER TABLE users DROP COLUMN username;
ALTER TABLE users DROP COLUMN password;
